version: '3.4'
 
networks:
  storeapi-dev:
    driver: nat 
 
services:
  storeapi:
    image: storeapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=52385;database=storedb;username=storeadmin;password=storeadmin"
    networks:
      - storeapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "52385:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/ :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "storeadmin"
      POSTGRES_PASSWORD: "storeadmin"
      POSTGRES_DB: "storedb"
    networks:
      - storeapi-dev
volumes:
  db_volume: